name: Django Deploy (Dockerfile Only)

on:
  push:
    branches:
      - master
      - github_action_test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Django tests
      run: |
        pip install -r requirements.txt
        python manage.py test

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker --version
          cd /app
          git pull origin master
          docker build -t kuop-api .
          docker stop kuop-api || true
          docker rm kuop-api || true
          docker run -d \
            --restart unless-stopped \
            -v /data/kuop:/app \
            --name kuop-api \
            -p 8000:8000 \
            kuop-api
